###

###
POST http://localhost:5281/api/User/register

{
  "firstName": "somename",
  "lastName": "somename",
  "email": "myemail@gmail.com",
  "address": {
    "street": "street",
    "city": "city",
    "country": "country"
  },
  "password": "Password1!
}